aula207/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='home'),
    path('<int:idPosts>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo'),
]

aula207/home/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.home, name='home'),
]

aula207/project/urls.py
from django.contrib import admin
from django.urls import path, include

# HTTP REQUEST <-> HTTP RESPONSE
# MODEL VIEW TEMPLATE variação de MODEL VIEW CONTROL
# MVT (MVC)


urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

aula207/blog/models.py
from django.db import models

# Create your models here.

aula207/home/models.py
from django.db import models

# Create your models here.

aula207/blog/views.py
from typing import Any

from django.shortcuts import render
from blog.data import posts
from django.http import HttpRequest, Http404


def blog(request):
    print('blog')

    context = {
        'text': 'Ola agora sou o blog',
        'title': 'Blog - ',
        'posts': posts
    }

    return render(request, 'blog/index.html', context)

def post(request: HttpRequest, idPosts: int):

    found_post: dict[str, Any] | None = None

    for post in posts:
        if post['id'] == idPosts:
            found_post = post
            break
    
    if found_post is None:
        raise Http404('Post não existe mermão')

    context = {
        'text': f'Aqui está o post número {idPosts}',
        'title': found_post['title'] + ' - ',
        'varpost': found_post
    }

    return render(request, 'blog/post.html', context)

def exemplo(request):
    print('blog')

    context = {
        'text': 'Ola agora sou o exemplo blog',
        'title': 'Exemplo - '
    }

    return render(request, 'blog/exemplo.html', context)

aula207/home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    print("HOME")

    context = {
        'text': 'Estamos na Home',
        'title': 'Index - ',
    }

    return render(request, 'home/index.html', context)

aula207/blog/templates/blog/exemplo.html
<!DOCTYPE html>
<html lang="en">
    {% include "global/partials/head.html" %}
    <body>
        {% include "global/partials/menu.html" %}
        <h1>{% block texto %} {{text}} {% endblock texto %}</h1>
    </body>
</html>

aula207/blog/templates/blog/index.html
{% extends "global/base.html" %} {% block texto %}Aqui o blog{% endblock texto%}

{% block posts %}
    {% for varpost in posts %}
        {% include "global/partials/postblock.html" %} 
    {% endfor %}
{% endblock posts %}

aula207/blog/templates/blog/post.html
{% extends "global/base.html" %} {% block texto %}Aqui o blog{% endblock texto%}

{% block posts %}
<article class="post single-post">
    <header>
        <h1 class="post__title">
            <a href="{% url "blog:post" varpost.id %}" >
                {{ varpost.title }}
            </a>
        </h1>
    </header>
    <div class="post__body">
        <p>
            {{varpost.body}}
        </p>
    </div>
</article>

{% endblock posts %}

aula207/home/templates/home/index.html
{% extends "global/base.html" %}

{% block texto %}{{ text }}{% endblock texto %}

{% block home %}
    <h1>HOME</h1>
{% endblock home %}